### ISSUE TITLE
Extension images dissapeard after JED update

### ISSUE THREAD

**Issue by n9iels** [joomla-extensions/install-from-web-client#10]
Hello,

I just noticed that, after the JED update, the images of the extensions are not correct loaded. The link to the images ends in a 404 not found.

Also a merry Christmas to everyone!

Greeting,
Niels

**Comment by nonumber** [comment]
Any update on this? Been 3 weeks now. Still not fixed...

**Comment by PhilETaylor** [comment]
@nonumber No commits since Nov 27, 2014 :-(

**Comment by coolbung** [comment]
This won't need a client update fortunately. The server side updates are close to done, would be great if someone can take a shot and close the remaining stuff, here's the PR for the things that are ready so far

https://github.com/joomla-extensions/install-from-web-server/pull/4

**Comment by beat** [comment]
As the Install-from-web code is open-source and publicly available, and help is welcome to get the full JED 3 support done. So please stop bumping and start helping: Take a look at @coolbung PR joomla-extensions/install-from-web-server#4 and help testing and polishing so that we can roll it out. Thanks!

**Comment by beat** [comment]
Done serverside, closing.
