### ISSUE TITLE
Removing install-from-web-server dependency

### ISSUE THREAD

**Issue by coolbung** [joomla-extensions/install-from-web-client#11]
Now that we have a chance to refactor the IFW, I propose that we get rid of the IFW server. The new JED has JSON APIs that we can directly use to create the views. I'm hoping that we can reuse the existing jlayouts and convert them into jquery templates (https://github.com/codepb/jquery-template/) in order to have the same look and feel to start with.

Let me know if you guys see any issues with this approach.

**Comment by nicksavov** [comment]
I think this would have to wait until the JED team releases the public API

**Comment by beat** [comment]
I'm fine with this as soon as the JED has a proper caching and caching CDN, allowing it for the same snappiness that we have with Install from web, and that is crucial to usability. The JED web-version is far from snappy for now, and that has a huge impact on Joomla.

The main reason of install-from-web-server was to provide a global html-rendered cache in CDN for all pages, so that from anywhere in the world the install-from-web-client is really very fast and feels "snappy" to use.

**Comment by HLeithner** [comment]
We are waiting for JED 4 for this topic, but it will not come for the j3 version of this plugin anymore. So I'm closing this here.
