### ISSUE TITLE
!!!! Who is in charge  here?

### ISSUE THREAD

**Issue by infograf768** [joomla-extensions/install-from-web-client#44]
As title says. No reply to issues and PRs.

For example, we need an update to let install in a 3.6.0 site... in
https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml

**Comment by brianteeman** [comment]
Earth calling @beat @coolbung

**Comment by beat** [comment]
The question of the subject "!!!! Who is in charge here?" has been correctly answered by @brianteeman just above.

All urgent PRs and issues have always been handled promptly (where the JED API allows the handling by the install-from-web function, and this is one of the most stable part of Joomla.

Thanks for reporting that on staging branch it doesn't install anymore. I have added a properly subject-named issue here and will handle it: #45

This document, specially first 3 paragraphs, answers the other parts of this issue:
https://www.joomla.org/about-joomla/the-project/code-of-conduct.html

As all the questions of this Issue have been answered and addressed, I'm now closing this issue.

**Comment by infograf768** [comment]
@beat 
Sorry it the title here looked a bit hard but may I direct you to issues that were never replied to or properly closed when the issue was solved.
Example:
https://github.com/joomla-extensions/install-from-web-client/issues/38
https://github.com/joomla-extensions/install-from-web-client/issues/13

**Comment by beat** [comment]
It is sure *much* better and *much more* constructive and positive to do a friendly reminder with a concrete list of forgotten things (we are all still humans) than to post a general negative subject :wink:  

#38 is a new effort to rewrite the install-from-web-client using directly JED API that has been paused because the JED API does not yet provide the required functionality.

#13 I have now replied on that. Sorry for not having replied earlier on this minor issue report. For sure with a PR we would have had testers and could have merged it.
