### ISSUE TITLE
Add Joomla 3.6 to list of compatible installation platforms

### ISSUE THREAD

**Issue by beat** [joomla-extensions/install-from-web-client#45]
We need to update needed to webinstaller.xml file.

I will do that in the next hours, and close this issue once done.

**Comment by mbabker** [comment]
> I will do that in the next hours

I didn't know 250+ hours counted as a few 😉 

Just a "playful" ping on this though.  Folks have been testing the 3.6 alpha and repeatedly bringing up the inability to install the plugin.

On a side note, any reason you don't use a regex like `3.[56789]` that way it defaults to being forward compatible, as extensions should be, instead of requiring man hours to make these updates with every minor release?

**Comment by coolbung** [comment]
Cool! So the XML definition supports regex for the version numbers ?

**Comment by mbabker** [comment]
Yep.  Languages have been using it for years (see https://update.joomla.org/language/details3/nl-BE_details.xml as an example).  Before 3.5 the regex could only be down to the minor version number but from 3.5 forward you can regex the entire version string and the `min_dev_level` and `max_dev_level` attributes on the `<targetplatform>` tag are deprecated in favor of full version regex.

**Comment by beat** [comment]
@mbabker I love "playful" :+1: ... Playful just doesn't rub in the wrong direction :smile: 

Thanks for your side-note too! I have now applied that too, and updated supported platforms up to 3.9 whatever that is, since Joomla 3.x must have B/C :smile: 

That closes this issue too :-)
